# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

name: Hello Dynamic

on:
  workflow_dispatch:
    inputs:
      NAME:
        type: string
        required: true
        description: Name to print
        default: "World"

defaults:
  run:
    shell: bash --noprofile --norc -o pipefail {0}

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print Words
        run: |
          echo "Hello ${{ github.event.inputs.NAME }}"
