# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

name: Hello

on:
  workflow_call:
    inputs:
      hello_name:
        type: string
        required: true
        description: Name to print
        default: "World"

defaults:
  run:
    shell: bash --noprofile --norc -o pipefail {0}

jobs:
  print_name:
    runs-on: ubuntu-latest
    env:
      hello_name: ${{ github.event.inputs.hello_name }}
    steps:
      - name: Print Hello
        run: |
          echo "Hello ${{ env.hello_name }}"
